Feature followship
thumperL/twitter-fullstack-2020 pull request #14
Opened 2021-03-04 10:20 UTC by linchuaccount

- 新增首頁右側"跟隨誰"名單
- 使用者可點擊"跟隨"按鈕，跟隨其他使用者
- 使用者可點擊"正在跟隨"按鈕，取消跟隨其他使用者

2021-03-04 12:47 UTC, thumperL requested changes
功能已測，基本上都沒有問題。
看到了list裡面都不會顯示到自己，非常好。

只有幾個小小的問題
- [x] followshipController檔案名稱拼錯了喔
- [ ] routes/modules/followships.js 裡面對controller的reference名稱記得改動
- [ ] 直接偷改form link去做follow自己的動作的話還是會過。提示：addFollowship進去先檢查 (req.user.id === req.params.userId)

2021-03-04 17:27 UTC, linchuaccount commented
已更新:
1. 修正檔名followshipController.js
2. 修正"跟隨誰"名單排列順序，順序會依照用戶被跟隨數從多到少排列，名單只顯示前10名用戶
3. 阻止用戶跟隨自己(待確認)

- 目前還沒實作"跟隨誰"名單下方的"顯示更多"按鈕功能

2021-03-05 04:46 UTC, newush approved these changes
- 功能確認沒問題

UI 問題（可加卡片後續再修）
- avatar 照片沒有顯示出來
- **顯示更多** 的連結即使沒有更多用戶，可能顏色要改變體驗會比較好。

2021-03-05 05:19 UTC, thumperL approved these changes
- 功能確定沒問題
- Self follow還是沒過，但是已經補上一個新的commit去做資料型態轉變並compare，self follow已經沒辦法被強制執行
- Avatar在我這裡看是沒問題的
- 顯示更多 的連結暫時先不處理，以開新的[Trello card](https://trello.com/c/KwKZy7Ij)

2021-03-05 05:22 UTC, merged