Feature account edit
thumperL/twitter-fullstack-2020 pull request #9
Opened 2021-03-01 07:05 UTC by newush

[Trello card](https://trello.com/c/56e4x0ys/5-%E4%BD%BF%E7%94%A8%E8%80%85%E8%83%BD%E7%B7%A8%E8%BC%AF%E8%87%AA%E5%B7%B1%E7%9A%84-account%E3%80%81name-email-%E5%92%8C-password)

- 使用者能編輯自己的 account、name, email 和 password
- 從設定連結可連到自己的帳戶頁面
- 進到設定頁面會帶出該用戶資料 account, name, email 但密碼為空
- 非該用戶會被擋住退到首頁 並出現錯誤 flash message
- 成功更新帳戶設定資料
- 提醒及阻擋錯誤行為： 
   a. 密碼與確認密碼不同
   b. 所有欄位不得為空白
   c. 與其它用戶重覆帳號或重覆Email （還在修 bug）

2021-03-01 22:08 UTC, thumperL requested changes
測試過了功能，以下幾點需要改動

- [x] 更改密碼會變成明碼儲存
- [x] 如果試圖access不存在的user id系統會error。可能在user.id !== req.user.id之前要有一個check，然後做一樣的error，只要不存在就回覆無法改動他人帳戶

2021-03-02 00:35 UTC, linchuaccount commented
確認可以修改使用者名稱、email、密碼如果使用者名稱和email和其他人重複會修改失敗

2021-03-02 19:54 UTC, newush commented
> 測試過了功能，以下幾點需要改動
> 
> * [ ]  更改密碼會變成明碼儲存
> * [ ]  如果試圖access不存在的user id系統會error。可能在user.id !== req.user.id之前要有一個check，然後做一樣的error，只要不存在就回覆無法改動他人帳戶

已修正 
i. 更改密碼會用加密儲存在資料庫
ii. 預防進入「不存在用戶的帳戶設定網頁」時程式會停住。加入阻擋和提示訊息

> 如果有修改資料，但帳號、名稱或email任一個沒有填資料(空白)送出，雖然會直接提示修改成功但其實並沒有修改到，或許可考慮在這幾格input標籤加上required，提醒使用者有資料沒填到

已修正
帳戶設定頁面帳號、名稱和 Email 在前端加上 required 不能有空白且出現提示，在後端保留若是空白更新則忽略（使用舊資料）

另外修正：column_setting 頁面顯示標題「帳戶設定」

2021-03-03 02:37 UTC, thumperL approved these changes
功能測試完畢，沒有問題！

2021-03-03 02:37 UTC, merged